name: 'Greetings'

on:
  fork:
  push:
    branches: [main]
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: EddieHubCommunity/gh-action-community/src/welcome@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |
            Congratulations, @${{ github.actor }}! 🎉 Thank you for creating your issue. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!

            We'd also like to invite you to our Discord server! Join us on [discord](https://discord.gg/Dy6xxxRD).
          pr-message: |
            Great job, @${{ github.actor }}! 🎉 Thank you for submitting your first pull request. Your contribution is valuable and we appreciate your efforts to improve our project.

            We'd also like to invite you to our Discord server! Join us [here](https://discord.gg/Dy6xxxRD).
          footer: 'We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/Satyam1923/Spring-Music-Player/blob/master/CONTRIBUTING.md)'